default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rest_api_guide_development
test:
  <<: *default
  database: rest_api_guide_test

production:
  <<: *default
  database: rest_api_guide_production
  username: rest_api_guide
  password: <%= ENV['REST_API_GUIDE_DATABASE_PASSWORD'] %>
